@echo off
echo Generating module_1__authentication___authorization...
call npx -y @mermaid-js/mermaid-cli -i "d:\For_Project\docs\diagrams\module_1__authentication___authorization.mmd" -o "d:\For_Project\docs\diagrams\module_1__authentication___authorization.png" -b transparent -s 2
echo Generating module_2__core_finance...
call npx -y @mermaid-js/mermaid-cli -i "d:\For_Project\docs\diagrams\module_2__core_finance.mmd" -o "d:\For_Project\docs\diagrams\module_2__core_finance.png" -b transparent -s 2
echo Generating module_3__share_funds...
call npx -y @mermaid-js/mermaid-cli -i "d:\For_Project\docs\diagrams\module_3__share_funds.mmd" -o "d:\For_Project\docs\diagrams\module_3__share_funds.png" -b transparent -s 2
echo Generating module_4__scheduler...
call npx -y @mermaid-js/mermaid-cli -i "d:\For_Project\docs\diagrams\module_4__scheduler.mmd" -o "d:\For_Project\docs\diagrams\module_4__scheduler.png" -b transparent -s 2
echo Generating module_5__support___system...
call npx -y @mermaid-js/mermaid-cli -i "d:\For_Project\docs\diagrams\module_5__support___system.mmd" -o "d:\For_Project\docs\diagrams\module_5__support___system.png" -b transparent -s 2
echo Generating module_5__knowledge_base__rag_...
call npx -y @mermaid-js/mermaid-cli -i "d:\For_Project\docs\diagrams\module_5__knowledge_base__rag_.mmd" -o "d:\For_Project\docs\diagrams\module_5__knowledge_base__rag_.png" -b transparent -s 2
echo Generating module_6__ai_chat___consultation...
call npx -y @mermaid-js/mermaid-cli -i "d:\For_Project\docs\diagrams\module_6__ai_chat___consultation.mmd" -o "d:\For_Project\docs\diagrams\module_6__ai_chat___consultation.png" -b transparent -s 2
echo Generating module_7__subscriptions___payments...
call npx -y @mermaid-js/mermaid-cli -i "d:\For_Project\docs\diagrams\module_7__subscriptions___payments.mmd" -o "d:\For_Project\docs\diagrams\module_7__subscriptions___payments.png" -b transparent -s 2
echo Generating module_8__notifications...
call npx -y @mermaid-js/mermaid-cli -i "d:\For_Project\docs\diagrams\module_8__notifications.mmd" -o "d:\For_Project\docs\diagrams\module_8__notifications.png" -b transparent -s 2
echo ALL DONE!
