// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/auth","id":"1"},"2":{"path":"/auth/login","parentId":"1","id":"2"},"3":{"path":"/auth/register","parentId":"1","id":"3"},"4":{"path":"/auth/forgot-password","parentId":"1","id":"4"},"5":{"path":"/auth/otp","parentId":"1","id":"5"},"6":{"path":"/","id":"6"},"7":{"path":"/","redirect":"/auth/login","parentId":"6","id":"7"},"8":{"path":"/dashboard","parentId":"6","id":"8"},"9":{"path":"/transactions","parentId":"6","id":"9"},"10":{"path":"funds","parentId":"6","id":"10"},"11":{"path":"/saving-goals","parentId":"6","id":"11"},"12":{"path":"/transactions","parentId":"6","id":"12"},"13":{"path":"/admin","id":"13"},"14":{"path":"/admin/users","parentId":"13","id":"14"}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "layouts__AuthLayout__index" */'@/layouts/AuthLayout/index.tsx')),
'2': React.lazy(() => import(/* webpackChunkName: "p__auth__login__index" */'@/pages/auth/login/index.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__auth__register__index" */'@/pages/auth/register/index.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__auth__forgot-password__index" */'@/pages/auth/forgot-password/index.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__auth__otp__index" */'@/pages/auth/otp/index.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "layouts__BasicLayout__index" */'@/layouts/BasicLayout/index.tsx')),
'7': React.lazy(() => import('./EmptyRoute')),
'8': React.lazy(() => import(/* webpackChunkName: "p__dashboard__index" */'@/pages/dashboard/index.tsx')),
'9': React.lazy(() => import(/* webpackChunkName: "p__transactions__index" */'@/pages/transactions/index.tsx')),
'10': React.lazy(() => import(/* webpackChunkName: "p__funds__index" */'@/pages/funds/index.tsx')),
'11': React.lazy(() => import(/* webpackChunkName: "p__saving-goals__index" */'@/pages/saving-goals/index.tsx')),
'12': React.lazy(() => import(/* webpackChunkName: "p__transactions__index" */'@/pages/transactions/index.tsx')),
'13': React.lazy(() => import(/* webpackChunkName: "layouts__AdminLayout__index" */'@/layouts/AdminLayout/index.tsx')),
'14': React.lazy(() => import(/* webpackChunkName: "p__admin__users__index" */'@/pages/admin/users/index.tsx')),
},
  };
}
