spring:
  datasource:
    password: 123456 # Điền mật khẩu database cục bộ của bạn ở đây
  mail:
    username: ${MAIL_USERNAME:hoangnv.private@gmail.com}
    password: ${MAIL_PASSWORD:jzohaqtkspgpffqg}
