// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/auth","id":"1"},"2":{"path":"/auth/login","parentId":"1","id":"2"},"3":{"path":"/auth/register","parentId":"1","id":"3"},"4":{"path":"/","id":"4"},"5":{"path":"/","redirect":"/dashboard","parentId":"4","id":"5"},"6":{"path":"/dashboard","parentId":"4","id":"6"}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "layouts__AuthLayout__index" */'@/layouts/AuthLayout/index.tsx')),
'2': React.lazy(() => import(/* webpackChunkName: "p__auth__login__index" */'@/pages/auth/login/index.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__auth__register__index" */'@/pages/auth/register/index.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "layouts__BasicLayout__index" */'@/layouts/BasicLayout/index.tsx')),
'5': React.lazy(() => import('./EmptyRoute')),
'6': React.lazy(() => import(/* webpackChunkName: "p__dashboard__index" */'@/pages/dashboard/index.tsx')),
},
  };
}
